# app/config/routing.yml
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#app_front:
#    resource: "@AppBundle/Controller/Frontend/"
#    type:     annotation
#app_back:
#    resource: "@AppBundle/Controller/Backend/"
#    type:     annotation
#    prefix: admin/

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:  /profile
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"

avanzu_admin_profile:
    path: /profile
avanzu_admin_logout:
    path: /logout